### ISSUE TITLE
That's pretty cool !

### ISSUE THREAD

**Issue by linskin** [Pablit0x/Dimensional-Feels#2]
I'm a student in China, yesterday our teacher asked us to make a notebook, so I logged into GitHub to find some inspiration, and then I saw your work, which was really amazing. I really like it. And thank you for your sharing and help. You are truly a generous person.

**Comment by Pablit0x** [comment]
Hey there!

First off, I'm super stoked to hear that you found my project helpful! 😊 It totally made my day to get your message. It's always awesome to know that the stuff I'm working on can inspire others, especially students like yourself.

By the way, I've recently pushed some major updates to the project. These changes might give you even more ideas for your notebook. Feel free to check them out and see if they spark any new inspiration.

Keep up the great work on your end, and never hesitate to reach out if you've got questions or just want to chat about coding and stuff. Happy coding!

**Comment by linskin** [comment]
Thank you for your message! Seeing your updates, I feel like I'm going to be busy. Haha, just kidding, but I'm really looking forward to seeing the new features."

**Comment by linskin** [comment]
Thank you for your message! Seeing your updates, I feel like I'm going to be busy. Haha, just kidding, but I'm really looking forward to seeing the new features.
